/** Generated by YAKINDU Statechart Tools code generator. */


#include "..\src\sc_types.h"

#include "mqtt_sc.h"

/*! \file Implementation of the state machine 'mqtt_sc'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_r1_GPRS_OFF_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_Not_conn_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_Connected_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_Connected_r2_credentials_default(Mqtt_sc* handle);
static void enseq_r1_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_default(Mqtt_sc* handle);
static void enseq_r1_GPRS_ON_r1_Connected_r2_default(Mqtt_sc* handle);
static void exseq_r1_GPRS_OFF(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1_Not_conn(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1_Connected(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1_Connected_r2_credentials(Mqtt_sc* handle);
static void exseq_r1(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1(Mqtt_sc* handle);
static void exseq_r1_GPRS_ON_r1_Connected_r2(Mqtt_sc* handle);
static void react_r1__entry_Default(Mqtt_sc* handle);
static void react_r1_GPRS_ON_r1_Connected_r2__entry_Default(Mqtt_sc* handle);
static void react_r1_GPRS_ON_r1__entry_Default(Mqtt_sc* handle);

/*! State machine reactions. */
static sc_boolean react(Mqtt_sc* handle);

/*! The reactions of state GPRS_OFF. */
static sc_boolean r1_GPRS_OFF_react(Mqtt_sc* handle, const sc_boolean try_transition);

/*! The reactions of state GPRS_ON. */
static sc_boolean r1_GPRS_ON_react(Mqtt_sc* handle, const sc_boolean try_transition);

/*! The reactions of state Not_conn. */
static sc_boolean r1_GPRS_ON_r1_Not_conn_react(Mqtt_sc* handle, const sc_boolean try_transition);

/*! The reactions of state Connected. */
static sc_boolean r1_GPRS_ON_r1_Connected_react(Mqtt_sc* handle, const sc_boolean try_transition);

/*! The reactions of state conn_to_broker. */
static sc_boolean r1_GPRS_ON_r1_Connected_r2_conn_to_broker_react(Mqtt_sc* handle, const sc_boolean try_transition);

/*! The reactions of state credentials. */
static sc_boolean r1_GPRS_ON_r1_Connected_r2_credentials_react(Mqtt_sc* handle, const sc_boolean try_transition);


static void clearInEvents(Mqtt_sc* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Mqtt_sc* handle);



static void mqtt_sc_eventqueue_init(mqtt_sc_eventqueue * eq, mqtt_sc_event *buffer, sc_integer capacity);
static sc_integer mqtt_sc_eventqueue_size(mqtt_sc_eventqueue * eq);
static void mqtt_sc_event_init(mqtt_sc_event * ev, Mqtt_scEventID name);
static mqtt_sc_event mqtt_sc_eventqueue_pop(mqtt_sc_eventqueue * eq);
static sc_boolean mqtt_sc_eventqueue_push(mqtt_sc_eventqueue * eq, mqtt_sc_event ev);
static void mqtt_sc_add_event_to_queue(mqtt_sc_eventqueue * eq, Mqtt_scEventID name);
static void mqtt_sc_dispatch_event(Mqtt_sc* handle, const mqtt_sc_event * event);
static mqtt_sc_event mqtt_sc_get_next_event(Mqtt_sc* handle);
static void mqtt_sc_dispatch_next_event(Mqtt_sc* handle);


void mqtt_sc_init(Mqtt_sc* handle)
{
	sc_integer i;
	
	for (i = 0; i < MQTT_SC_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Mqtt_sc_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	
	
	handle->isExecuting = bool_false;
	mqtt_sc_eventqueue_init(&handle->in_event_queue, handle->in_buffer, MQTT_SC_IN_EVENTQUEUE_BUFFERSIZE);
}

void mqtt_sc_enter(Mqtt_sc* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart mqtt_sc */
	enseq_r1_default(handle);
	handle->isExecuting = bool_false;
}

void mqtt_sc_exit(Mqtt_sc* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart mqtt_sc */
	exseq_r1(handle);
	handle->isExecuting = bool_false;
}


sc_boolean mqtt_sc_is_active(const Mqtt_sc* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < MQTT_SC_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Mqtt_sc_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean mqtt_sc_is_final(const Mqtt_sc* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean mqtt_sc_is_state_active(const Mqtt_sc* handle, Mqtt_scStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Mqtt_sc_r1_GPRS_OFF :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_OFF] == Mqtt_sc_r1_GPRS_OFF
			);
			break;
		case Mqtt_sc_r1_GPRS_ON :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON] >= Mqtt_sc_r1_GPRS_ON
				&& handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON] <= Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials);
			break;
		case Mqtt_sc_r1_GPRS_ON_r1_Not_conn :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON_R1_NOT_CONN] == Mqtt_sc_r1_GPRS_ON_r1_Not_conn
			);
			break;
		case Mqtt_sc_r1_GPRS_ON_r1_Connected :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON_R1_CONNECTED] >= Mqtt_sc_r1_GPRS_ON_r1_Connected
				&& handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON_R1_CONNECTED] <= Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials);
			break;
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON_R1_CONNECTED_R2_CONN_TO_BROKER] == Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker
			);
			break;
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MQTT_SC_R1_GPRS_ON_R1_CONNECTED_R2_CREDENTIALS] == Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Mqtt_sc* handle)
{
	handle->iface.conn_to_op_raised = bool_false;
	handle->iface.gprs_on_raised = bool_false;
	handle->iface.cred_rcv_raised = bool_false;
	handle->iface.publish_var_raised = bool_false;
	handle->iface.publish_id_raised = bool_false;
	handle->iface.publish_sett_raised = bool_false;
}

static void run_cycle(Mqtt_sc* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	mqtt_sc_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < MQTT_SC_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Mqtt_sc_r1_GPRS_OFF:
			{
				r1_GPRS_OFF_react(handle, bool_true);
				break;
			}
			case Mqtt_sc_r1_GPRS_ON_r1_Not_conn:
			{
				r1_GPRS_ON_r1_Not_conn_react(handle, bool_true);
				break;
			}
			case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker:
			{
				r1_GPRS_ON_r1_Connected_r2_conn_to_broker_react(handle, bool_true);
				break;
			}
			case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials:
			{
				r1_GPRS_ON_r1_Connected_r2_credentials_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		mqtt_sc_dispatch_next_event(handle);
	} while ((((((handle->iface.conn_to_op_raised == bool_true) || (handle->iface.gprs_on_raised == bool_true)) || (handle->iface.cred_rcv_raised == bool_true)) || (handle->iface.publish_var_raised == bool_true)) || (handle->iface.publish_id_raised == bool_true)) || (handle->iface.publish_sett_raised == bool_true));
	handle->isExecuting = bool_false;
}


void mqtt_sc_raise_conn_to_op(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_conn_to_op);
	run_cycle(handle);
}

void mqtt_sc_raise_gprs_on(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_gprs_on);
	run_cycle(handle);
}

void mqtt_sc_raise_cred_rcv(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_cred_rcv);
	run_cycle(handle);
}

void mqtt_sc_raise_publish_var(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_publish_var);
	run_cycle(handle);
}

void mqtt_sc_raise_publish_id(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_publish_id);
	run_cycle(handle);
}

void mqtt_sc_raise_publish_sett(Mqtt_sc* handle)
{
	mqtt_sc_add_event_to_queue(&(handle->in_event_queue), Mqtt_sc_publish_sett);
	run_cycle(handle);
}




/* implementations of all internal functions */

/* 'default' enter sequence for state GPRS_OFF */
static void enseq_r1_GPRS_OFF_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state GPRS_OFF */
	handle->stateConfVector[0] = Mqtt_sc_r1_GPRS_OFF;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state GPRS_ON */
static void enseq_r1_GPRS_ON_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state GPRS_ON */
	enseq_r1_GPRS_ON_r1_default(handle);
}

/* 'default' enter sequence for state Not_conn */
static void enseq_r1_GPRS_ON_r1_Not_conn_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state Not_conn */
	handle->stateConfVector[0] = Mqtt_sc_r1_GPRS_ON_r1_Not_conn;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Connected */
static void enseq_r1_GPRS_ON_r1_Connected_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state Connected */
	enseq_r1_GPRS_ON_r1_Connected_r2_default(handle);
}

/* 'default' enter sequence for state conn_to_broker */
static void enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state conn_to_broker */
	handle->stateConfVector[0] = Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state credentials */
static void enseq_r1_GPRS_ON_r1_Connected_r2_credentials_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for state credentials */
	handle->stateConfVector[0] = Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region r1 */
static void enseq_r1_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for region r1 */
	react_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_r1_GPRS_ON_r1_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for region r1 */
	react_r1_GPRS_ON_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r2 */
static void enseq_r1_GPRS_ON_r1_Connected_r2_default(Mqtt_sc* handle)
{
	/* 'default' enter sequence for region r2 */
	react_r1_GPRS_ON_r1_Connected_r2__entry_Default(handle);
}

/* Default exit sequence for state GPRS_OFF */
static void exseq_r1_GPRS_OFF(Mqtt_sc* handle)
{
	/* Default exit sequence for state GPRS_OFF */
	handle->stateConfVector[0] = Mqtt_sc_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state GPRS_ON */
static void exseq_r1_GPRS_ON(Mqtt_sc* handle)
{
	/* Default exit sequence for state GPRS_ON */
	exseq_r1_GPRS_ON_r1(handle);
}

/* Default exit sequence for state Not_conn */
static void exseq_r1_GPRS_ON_r1_Not_conn(Mqtt_sc* handle)
{
	/* Default exit sequence for state Not_conn */
	handle->stateConfVector[0] = Mqtt_sc_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state Connected */
static void exseq_r1_GPRS_ON_r1_Connected(Mqtt_sc* handle)
{
	/* Default exit sequence for state Connected */
	exseq_r1_GPRS_ON_r1_Connected_r2(handle);
}

/* Default exit sequence for state conn_to_broker */
static void exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(Mqtt_sc* handle)
{
	/* Default exit sequence for state conn_to_broker */
	handle->stateConfVector[0] = Mqtt_sc_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state credentials */
static void exseq_r1_GPRS_ON_r1_Connected_r2_credentials(Mqtt_sc* handle)
{
	/* Default exit sequence for state credentials */
	handle->stateConfVector[0] = Mqtt_sc_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region r1 */
static void exseq_r1(Mqtt_sc* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of mqtt_sc.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Mqtt_sc_r1_GPRS_OFF :
		{
			exseq_r1_GPRS_OFF(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Not_conn :
		{
			exseq_r1_GPRS_ON_r1_Not_conn(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_credentials(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_r1_GPRS_ON_r1(Mqtt_sc* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of mqtt_sc.r1.GPRS_ON.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Mqtt_sc_r1_GPRS_ON_r1_Not_conn :
		{
			exseq_r1_GPRS_ON_r1_Not_conn(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_credentials(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r2 */
static void exseq_r1_GPRS_ON_r1_Connected_r2(Mqtt_sc* handle)
{
	/* Default exit sequence for region r2 */
	/* Handle exit of all possible states (of mqtt_sc.r1.GPRS_ON.r1.Connected.r2) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_conn_to_broker :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
			break;
		}
		case Mqtt_sc_r1_GPRS_ON_r1_Connected_r2_credentials :
		{
			exseq_r1_GPRS_ON_r1_Connected_r2_credentials(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_r1__entry_Default(Mqtt_sc* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r1_GPRS_OFF_default(handle);
}

/* Default react sequence for initial entry  */
static void react_r1_GPRS_ON_r1_Connected_r2__entry_Default(Mqtt_sc* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r1_GPRS_ON_r1_Connected_r2_credentials_default(handle);
}

/* Default react sequence for initial entry  */
static void react_r1_GPRS_ON_r1__entry_Default(Mqtt_sc* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r1_GPRS_ON_r1_Not_conn_default(handle);
}


static sc_boolean react(Mqtt_sc* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean r1_GPRS_OFF_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state GPRS_OFF. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.gprs_on_raised == bool_true)
			{ 
				exseq_r1_GPRS_OFF(handle);
				enseq_r1_GPRS_ON_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean r1_GPRS_ON_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state GPRS_ON. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.gprs_on_raised == bool_true)
			{ 
				exseq_r1_GPRS_ON(handle);
				enseq_r1_GPRS_OFF_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean r1_GPRS_ON_r1_Not_conn_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state Not_conn. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((r1_GPRS_ON_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->iface.conn_to_op_raised == bool_true)
			{ 
				exseq_r1_GPRS_ON_r1_Not_conn(handle);
				enseq_r1_GPRS_ON_r1_Connected_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean r1_GPRS_ON_r1_Connected_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state Connected. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((r1_GPRS_ON_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->iface.conn_to_op_raised == bool_true)
			{ 
				exseq_r1_GPRS_ON_r1_Connected(handle);
				enseq_r1_GPRS_ON_r1_Not_conn_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean r1_GPRS_ON_r1_Connected_r2_conn_to_broker_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state conn_to_broker. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((r1_GPRS_ON_r1_Connected_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->iface.publish_var_raised == bool_true)
			{ 
				exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
				enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(handle);
			}  else
			{
				if (handle->iface.publish_id_raised == bool_true)
				{ 
					exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
					enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(handle);
				}  else
				{
					if (handle->iface.publish_sett_raised == bool_true)
					{ 
						exseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker(handle);
						enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(handle);
					}  else
					{
						did_transition = bool_false;
					}
				}
			}
		} 
	} return did_transition;
}

static sc_boolean r1_GPRS_ON_r1_Connected_r2_credentials_react(Mqtt_sc* handle, const sc_boolean try_transition)
{
	/* The reactions of state credentials. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((r1_GPRS_ON_r1_Connected_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->iface.cred_rcv_raised == bool_true)
			{ 
				exseq_r1_GPRS_ON_r1_Connected_r2_credentials(handle);
				enseq_r1_GPRS_ON_r1_Connected_r2_conn_to_broker_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}




static void mqtt_sc_eventqueue_init(mqtt_sc_eventqueue * eq, mqtt_sc_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer mqtt_sc_eventqueue_size(mqtt_sc_eventqueue * eq)
{
	return eq->size;
}

static mqtt_sc_event mqtt_sc_eventqueue_pop(mqtt_sc_eventqueue * eq)
{
	mqtt_sc_event event;
	if(mqtt_sc_eventqueue_size(eq) <= 0) {
		mqtt_sc_event_init(&event, Mqtt_sc_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean mqtt_sc_eventqueue_push(mqtt_sc_eventqueue * eq, mqtt_sc_event ev)
{
	if(mqtt_sc_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void mqtt_sc_event_init(mqtt_sc_event * ev, Mqtt_scEventID name)
{
	ev->name = name;
}

static void mqtt_sc_add_event_to_queue(mqtt_sc_eventqueue * eq, Mqtt_scEventID name)
{
	mqtt_sc_event event;
	mqtt_sc_event_init(&event, name);
	mqtt_sc_eventqueue_push(eq, event);
}

static void mqtt_sc_dispatch_event(Mqtt_sc* handle, const mqtt_sc_event * event) {
	switch(event->name) {
		case Mqtt_sc_conn_to_op:
		{
			handle->iface.conn_to_op_raised = bool_true;
			break;
		}
		case Mqtt_sc_gprs_on:
		{
			handle->iface.gprs_on_raised = bool_true;
			break;
		}
		case Mqtt_sc_cred_rcv:
		{
			handle->iface.cred_rcv_raised = bool_true;
			break;
		}
		case Mqtt_sc_publish_var:
		{
			handle->iface.publish_var_raised = bool_true;
			break;
		}
		case Mqtt_sc_publish_id:
		{
			handle->iface.publish_id_raised = bool_true;
			break;
		}
		case Mqtt_sc_publish_sett:
		{
			handle->iface.publish_sett_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static mqtt_sc_event mqtt_sc_get_next_event(Mqtt_sc* handle)
{
	mqtt_sc_event next_event;
	mqtt_sc_event_init(&next_event, Mqtt_sc_invalid_event);
	if(mqtt_sc_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = mqtt_sc_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void mqtt_sc_dispatch_next_event(Mqtt_sc* handle)
{
	mqtt_sc_event nextEvent;
	nextEvent = mqtt_sc_get_next_event(handle);
	mqtt_sc_dispatch_event(handle, &nextEvent);
}
